workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Prepare environment
        script: |
          chmod +x gradlew
          chmod +x android/gradlew
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --non-interactive
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk 