workflows:
  build-android:
    name: Build Android APK
    triggers:
      - push
      - pull_request
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Prepare Android build
        script: |
          npx expo prebuild --platform android --non-interactive
          chmod +x android/gradlew
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk 