workflows:
  expo-android:
    name: Expo React Native Android Build
    triggering:
      events:
        - push
    environment:
      node: "18.17.0"
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Install expo-cli
        script: npm install -g expo-cli
      - name: Prebuild Android
        script: expo prebuild --platform android
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk 