workflows:
  expo-android:
    name: Expo React Native Android Build
    triggering:
      events:
        - push
    environment:
      node: "18.16.0"
      expo: "latest"
      cocoapods: default
      android:
        gradle: default
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Install expo-cli
        script: npm install -g expo-cli
      - name: Prebuild Android
        script: expo prebuild --platform android
      - name: Build Android release bundle
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab 