name: Build APK

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd android && ./gradlew clean || true

      - name: Create google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "example-app",
              "storage_bucket": "example-app.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:abcdef123456789",
                  "android_client_info": {
                    "package_name": "com.bigshow"
                  }
                }
              }
            ]
          }' > android/app/google-services.json

      - name: Fix React Native Gradle Plugin
        run: |
          echo "Fixing React Native Gradle Plugin..."
          PLUGIN_FILE="node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts"
          if [ -f "$PLUGIN_FILE" ]; then
            # Create backup
            cp "$PLUGIN_FILE" "${PLUGIN_FILE}.bak"
            # Copy our fixed file
            cp fixed-plugin.gradle.kts "$PLUGIN_FILE"
            echo "Successfully replaced plugin file"
          else
            echo "Plugin file not found at $PLUGIN_FILE"
          fi

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Grant execution permission for Gradle wrapper
        run: chmod +x android/gradlew || echo "Could not set permissions on gradlew"

      - name: Update Gradle Properties
        run: |
          echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "kotlin.incremental=false" >> android/gradle.properties
          echo "reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64" >> android/gradle.properties

      - name: Build release APK
        working-directory: android
        run: |
          # Debug info
          ./gradlew --version
          
          # Build with detailed error reporting
          ./gradlew assembleRelease --no-daemon --stacktrace -Dorg.gradle.logging.level=debug

      - name: Find and upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab 