name: Build APK

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd android && ./gradlew clean || true

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: List android directory
        run: ls -la android || echo "Android directory not found"

      - name: Grant execution permission for Gradle wrapper
        run: chmod +x android/gradlew || echo "Could not set permissions on gradlew"

      - name: Build release APK
        working-directory: android
        run: ./gradlew assembleRelease --info

      - name: Debug - List output directories
        run: |
          echo "Checking if output directories exist:"
          ls -la android/app/build || echo "build directory not found"
          ls -la android/app/build/outputs || echo "outputs directory not found"
          ls -la android/app/build/outputs/apk || echo "apk directory not found"
          ls -la android/app/build/outputs/apk/release || echo "release directory not found" 