name: Build APK

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Create google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "example-app",
              "storage_bucket": "example-app.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:abcdef123456789",
                  "android_client_info": {
                    "package_name": "com.bigshow"
                  }
                }
              }
            ]
          }' > android/app/google-services.json

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Replace RN Gradle Plugin build file
        run: |
          cp .github/scripts/correct_react_native_gradle_plugin.kts \
             node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts
          echo "Replaced RN Gradle Plugin build.gradle.kts with corrected version"
          head -n 20 node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts

      - name: Update Gradle wrapper to 7.5.1
        run: |
          mkdir -p android/gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          chmod +x android/gradlew

      - name: Configure android/gradle.properties
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8" > android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64" >> android/gradle.properties
          echo "newArchEnabled=false" >> android/gradle.properties
          echo "hermesEnabled=true" >> android/gradle.properties
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "kotlin.incremental=false" >> android/gradle.properties
          echo "FLIPPER_VERSION=0.202.0" >> android/gradle.properties

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease --info --no-daemon --stacktrace

      - name: Find and upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab 