name: Build APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Create google-services.json (if needed)
      run: |
        if [ ! -f android/app/google-services.json ]; then
          echo '{"project_info":{"project_number":"","project_id":"","storage_bucket":""},"client":[{"client_info":{"mobilesdk_app_id":"","android_client_info":{"package_name":"com.bigshow"}},"oauth_client":[],"api_key":[{"current_key":""}],"services":{"appinvite_service":{"other_platform_oauth_client":[]}}}],"configuration_version":"1"}' > android/app/google-services.json
        fi
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Clean project
      run: |
        cd android
        ./gradlew clean
        
    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: List APK files (Debug)
      run: |
        find android -name "*.apk" -type f
        ls -la android/app/build/outputs/apk/release/ || echo "Release directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Upload APK (Alternative path)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk-files
        path: android/app/build/outputs/apk/**/*.apk
        retention-days: 7 