name: EAS Build APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK with EAS
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            echo "Get your token from: expo login --username YOUR_USERNAME then expo whoami --token"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run prepare-eas-build script
        run: npm run prepare-eas-build

      - name: Build Android APK (Preview)
        run: npm run build:preview

      - name: Download latest build
        run: |
          # Get the latest build ID
          BUILD_ID=$(eas build:list --status finished --platform android --non-interactive --json | jq -r '.[0].id')
          echo "Latest build ID: $BUILD_ID"
          
          # Create download directory
          mkdir -p downloads
          
          # Download the build
          eas build:download --id $BUILD_ID --output downloads/app-preview.apk --non-interactive
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-preview-apk
          path: downloads/app-preview.apk
          retention-days: 30 